export const erros = {
    "INVALID_EMAIL" : "E-MAIL INFORMADO INVALIDO",
    "INVALID_PASSWORD" : "A SENHA INFORMADA NAO ATENDE OS PADROES",
    "EMPTY_STRING": "O VALOR DA STRING NAO PODE SER VAZIO"
}