export const erros = {
    "INVALID_EMAIL" : "E-MAIL INFORMADO INVALIDO",
    "INVALID_PASSWORD" : "A SENHA INFORMADA NAO ATENDE OS PADROES",
    "EMPTY_STRING": "O VALOR DA STRING NAO PODE SER VAZIO",
    "INVALID_NUMBER" : "O VALOR NAO PODE SER MENOR QUE 0",
    "NOT_A_NUMBER": "O VALOR PRECISA SER NUMERICO",
    "EMPTY_ARRAY": "O ARRAY NAO PODE SER VAZIO"
}